### PR TITLE
ci: fix failed tests with tarantool 3.2.0

### PR DESCRIPTION
**Pull request by themilchenko**
There are a few failed tests with replacing tarantool sdk version in CI workflow from 3.0.0 into 3.2.0.

After the patch all failed tests related with the upgrade was fixed.

Part of https://github.com/tarantool/tt/issues/931

### CODE REVIEW

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
Please split the commit into two or three separate commits based on its purpose/problems its solve. And describe the problems into the commit messages.

**Comment by oleg-jukovec** [comment]
`in previous tarantool 3.0.0 skd` -> `in previous tarantool 3.0.0 sdk`

**Review by oleg-jukovec — APPROVED** [review]
LGTM!

**Comment by themilchenko** [comment]
> `in previous tarantool 3.0.0 skd` -> `in previous tarantool 3.0.0 sdk`

Corrected, thank you!

**Review by DerekBum — APPROVED** [review]

**Pull request merged**
