### PR TITLE
deps: bump go-openssl to v1.1.1

### PR DESCRIPTION
**Pull request by oleg-jukovec**
The latest version fixes a svacer issues.

### CODE REVIEW

**Review by dmyger — APPROVED** [review]
Won't there be a problem with 22 Ubuntu like there used to be?

**Comment by oleg-jukovec** [comment]
> Won't there be a problem with 22 Ubuntu like there used to be?

I think we can wait for problems to solve it. `tt-ee` is testing and building under ubuntu-22.04 and all is fine.

**Review by DerekBum — APPROVED** [review]
What about this file? Is it used in those workflows? Don't we need to update Ubuntu version here as well?
https://github.com/tarantool/tt/blob/bb933927617a81ef5ff6398ae05a6e2969fd2977/ci/Dockerfile#L1-L6

**Comment by oleg-jukovec** [comment]
> What about this file? Is it used in those workflows? Don't we need to update Ubuntu version here as well?
> 
> https://github.com/tarantool/tt/blob/bb933927617a81ef5ff6398ae05a6e2969fd2977/ci/Dockerfile#L1-L6

https://github.com/tarantool/tt/blob/bb933927617a81ef5ff6398ae05a6e2969fd2977/ci/Dockerfile#L63-L69

It installs OpenSSL 3.0.8 directly, so it should work fine.

**Comment by oleg-jukovec** [comment]
Yeah, it works:

https://github.com/tarantool/tt/actions/runs/11719705206/job/32643535109
https://github.com/tarantool/tt/actions/runs/11719705206/job/32643535654

**Pull request merged**
