### PR TITLE
start: fix start Tarantool 3 with encrypted etcd

### LINKED ISSUE #938: start: failed to start Tarantool 3 with encrypted etcd
Config file:
```yaml
config:
  etcd:
    endpoints:
    - https://localhost:2379
    ssl:
      verify_peer: false
      ca_file: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/ca.crt
      ssl_key: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/localhost.key
      ca_path: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert
      verify_host: false
      ssl_cert: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/localhost.crt
    prefix: /cluster_a/
```

```bash
tt start test_app
```
```
   ⨯ can't collect instance information for test_app: error loading instance "cluster_a-storage-2-2" configuration from config "/home/moiseevgeorgy/Development/github/tarantool/cluster-federation/instances.enabled/test_app/config.yaml": unable to connect to etcd: fail to create tls client config: KeyFile and CertFile must both be present[key: /home/moiseevgeorgy/Development/github/tarantool/cluster-federation/test/integration/ssl_cert/localhost.key, cert: ]
```

### PR DESCRIPTION
**Pull request by patapenka-alexey**
This patch fixes an incorrect SSL certificate parameter name.

Closes #938

### CODE REVIEW

**Review by themilchenko — COMMENTED** [review]
Please, add a CHANGELOG entry.

**Review by themilchenko — COMMENTED** [review]
I forgot to tell that it would also be great to write an integration test for this fix to make sure everything works well.

**Comment by oleg-jukovec** [comment]
> I forgot to tell that it would also be great to write an integration test for this fix to make sure everything works well.

We don't have such integration tests now: part/full configuration is stored in an external storage. So it could be non-trivial.
Let's write such tests in a separate task.

@patapenka-alexey please, create an issue to create integration tests: `tt start/stop` + a configuration locates in `etcd/tcs` with/without TLS.

**Review by oleg-jukovec — APPROVED** [review]
Please, change the commit title:

`start: failed to start Tarantool 3 with encrypted etcd` -> 
`start: fix start Tarantool 3 with encrypted etcd`

**Comment by themilchenko** [comment]
> > I forgot to tell that it would also be great to write an integration test for this fix to make sure everything works well.
> 
> 
> 
> We don't have such integration tests now: part/full configuration is stored in an external storage. So it could be non-trivial.
> 
> Let's write such tests in a separate task.
> 
> 
> 
> @patapenka-alexey please, create an issue to create integration tests: `tt start/stop` + a configuration locates in `etcd/tcs` with/without TLS.

Oh, got it. Sorry for misleading.

**Review by themilchenko — APPROVED** [review]

**Pull request merged**
