### PR TITLE
generate: autoupdate

### PR DESCRIPTION
**Pull request by TarantoolBot**
Automated changes by [update](https://github.com/tarantool/tt/blob/master/.github/workflows/update.yml) job.

### CODE REVIEW

**Comment by oleg-jukovec** [comment]
We are waiting for a Tarantool's release here.

**Comment by Totktonada** [comment]
> We are waiting for a Tarantool's release here.

I would like to hear a motivation behind this decision.

I see some positive effects from the rolling update.

* When tarantool is released, there is a tt release that is ready to work with it. (It is even possible that this tt release is already used by a customer.)
* An attempt to use new tarantool feature doesn't fail any config validation.
* tt can implement a new functionality that depends on an unreleased tarantool version.

What are downsides?

* A new option passes validation even if tarantool doesn't support it.

But it is possible anyway with tt that is modern enough and tarantool that is old enough.

**Comment by oleg-jukovec** [comment]
> What are downsides?

The option could be changed after the first introduce and before the release. We already have some problems with iproto.listen on Tarantool 3.0.

**Comment by Totktonada** [comment]
> A configuration option could be changed after a first introduce and before the release. We already had some problems with iproto.listen on Tarantool 3.0.
>
> Release cycles of the Tarantool and the tt are not synced, so we could have some release version of `tt` that works incorrectly for a new release version of the Tarantool.

Thanks for the clarification! Fair points.

Changing of a functionality that was not released yet occurs rarely, but it is acceptable.

**Comment by oleg-jukovec** [comment]
Tarantool 3.2 released. The time has come.

**Review by oleg-jukovec — APPROVED** [review]

**Pull request merged**
